name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build Fablo
        run: |
          shellcheck --version && \
          yamllint -v && \
          npm install && \
          npm run build && \
          ./fablo-build.sh

      - name: Test sample network
        run: e2e-network/docker/sample.sh

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-05-version3-BFT-snapshot
          path: |
            e2e-network/docker/test-05-version3-BFT-snapshot.sh.logs/*
            e2e-network/docker/test-05-version3-BFT-snapshot.sh.tmpdir/fablo-target/**/*
